### PR TITLE
generator function related fixes

### LINKED ISSUE #708: feature: support correct call graphs for generator and async generator functions
* [x] add virtual contexts between `YieldExpression`s
* [x] establish meaningful parent/child relationship with generator function's virtual contexts and callers of its `next` function
  * → `realContext` is now the **first** child context of generator and async functions
* [x] add support for async generator functions

## Future Work

* Add proper data flow for arguments and return value of `yield`: https://github.com/Domiii/dbux/issues/521

### PR DESCRIPTION
**Pull request by MiccWan**
#708

### CODE REVIEW

File: dbux-data/src/callGraph/CallGraph.js [hunk 1]
```diff
@@ -262,14 +262,16 @@ export default class CallGraph {
     const trace = this.dp.collections.traces.getById(traceId);
     const realContextId = this.dp.util.getRealContextIdOfTrace(traceId);
     const parentTraces = this.dp.indexes.traces.parentsByRealContext.get(realContextId) || EmptyArray;
+    const callerTraces = parentTraces.map(t => this.dp.util.getPreviousCallerTraceOfTrace(t.traceId))
```
Comment (Domiii) [inline dbux-data/src/callGraph/CallGraph.js:265]: Why do we have both, `parentTraces` + `callerTraces`?

File: dbux-data/src/impl/indexes/ParentTracesInRealContextIndex.js [hunk 2]
```diff
@@ -34,9 +34,9 @@ export default class ParentTracesInRealContextIndex extends CollectionIndex {
          */
         added: (contexts) => {
           for (const context of contexts) {
-            const { parentTraceId, contextType } = context;
-            // skip parent trace of virtualContext
-            if (isVirtualContextType(contextType)) {
+            const { parentTraceId, contextId } = context;
+            // skip empty contexts
+            if (this.dp.indexes.traces.byContext.getSize(contextId) === 0) {
```
Comment (Domiii) [inline dbux-data/src/impl/indexes/ParentTracesInRealContextIndex.js:39]: Why allow contexts for which `isVirtualContextType` is `true`?

**Review by Domiii — CHANGES_REQUESTED** [review]

File: dbux-data/src/callGraph/CallGraph.js (hunk 1 above)
Comment (MiccWan) [reply dbux-data/src/callGraph/CallGraph.js:265]: Yes this should be fixed. Previously, `ExecutionContext.parentTraceId` might be an `Argument` trace rather than a `BCE` trace, so `dp.util.getPreviousCallerTraceOfTrace` is used to find the actuall BCE (in similar function `_getNextChildTrace` so I copied the code from that). But now `parentTraceId` is the actual BCE if the context is created by a `CE`, so we may remove the function here.

File: dbux-data/src/impl/indexes/ParentTracesInRealContextIndex.js (hunk 2 above)
Comment (MiccWan) [reply dbux-data/src/impl/indexes/ParentTracesInRealContextIndex.js:39]: This index is used to find all caller trace of real contexts. We want to register the **first** virtual context(`ResumeAsync`, `ResumeGen`, `ResumeAsyncGen`, but not `Await`), but not the following virtual contexts. The following contexts do not have `parentTraceId` so they will be filtered out this way. And `Await` contexts have no children, so check size of `traces.byContext` index will filter them out.
Maybe the name itself is ambiguous, I'll try to rename them.
