### PR TITLE
ACG fixes

### LINKED ISSUE #702: fix ACS
* [ ] test w/ `sequelize#2`
  * select the 4th error (actual reported error)
* [ ] The stack only goes full width after also clicking the CG buttons.
  * [ ] Afterwards, the CG button is still shown as active
* [ ] `executeSql()` is not a CGR. It's actual CGR shows up when clicking into it.
* [ ] TODO: some more inconsistencies

### PR DESCRIPTION
**Pull request by MiccWan**
also:
* fix `ContextFilter` not using default config
* fix SearchButton not closing search menu
* hide annotate buttons

#702

### CODE REVIEW

File: dbux-graph-client/src/graph/asyncGraph/AsyncGraph.js [hunk 1]
```diff
@@ -522,8 +528,13 @@ class AsyncGraph extends GraphBase {
...
         values.forEach(({ applicationId, asyncNodeId, label, valueTraceId }) => {
           const asyncNodeData = this.allNodeData.get(applicationId, asyncNodeId);
-          asyncNodeData.valueLabel = label;
-          asyncNodeData.valueTraceId = valueTraceId;
+          if (asyncNodeData) {
+            asyncNodeData.valueLabel = label;
+            asyncNodeData.valueTraceId = valueTraceId;
+          }
+          else {
+            this.logger.warn(`[updateRootValueLabel] update before asyncNodeData is set.`);
```
Comment (Domiii) [inline dbux-graph-client/src/graph/asyncGraph/AsyncGraph.js:536]: @MiccWan We might want to put this behind a `Verbose` flag or so?
