### PR TITLE
misc fixes

### LINKED ISSUE #702: fix ACS
* [ ] test w/ `sequelize#2`
  * select the 4th error (actual reported error)
* [ ] The stack only goes full width after also clicking the CG buttons.
  * [ ] Afterwards, the CG button is still shown as active
* [ ] `executeSql()` is not a CGR. It's actual CGR shows up when clicking into it.
* [ ] TODO: some more inconsistencies

### PR DESCRIPTION
**Pull request by MiccWan**
#702

### CODE REVIEW

File: dbux-code/src/codeUtil/treeView/BaseTreeViewNodeProvider.js [hunk 1]
```diff
@@ -418,15 +428,19 @@ export default class BaseTreeViewNodeProvider {
...
-   * @param {BaseTreeViewNode} parent 
+   * @param {BaseTreeViewNode} parent
    * @return {BaseTreeViewNode}
    */
-  getNodeByClass(clazz, parent = null) {
-    let children = this.rootNodes;
-    if (parent) {
-      children = parent.children;
-    }
+  getChildByClass(clazz, parent) {
```
Comment (Domiii) [inline dbux-code/src/codeUtil/treeView/BaseTreeViewNodeProvider.js:434]: @MiccWan  move to `BaseTreeViewNode`

File: dbux-code/src/globalAnalysisView/GlobalAnalysisViewController.js [hunk 2]
```diff
@@ -49,8 +50,18 @@ export default class GlobalAnalysisViewController {
    *  #########################################################################*/
 
   async focusOnSearchResult() {
-    const searchResultNode = this.treeDataProvider.getNodeByClass(GlobalSearchNode);
-    await this.treeView.reveal(searchResultNode, { select: false, expand: 1 });
+    const searchResultNode = this.treeDataProvider.getRootByClass(GlobalSearchNode);
+    try {
```
Comment (Domiii) [inline dbux-code/src/globalAnalysisView/GlobalAnalysisViewController.js:54]: @MiccWan  `if (!this.treeView.visible) { return; }`

File: dbux-common/src/util/TriggerablePromise.js [hunk 3]
```diff
@@ -0,0 +1,55 @@
+import sleep from './sleep';
+
+export default class TriggerablePromise {
```
Comment (Domiii) [inline dbux-common/src/util/TriggerablePromise.js:3]: rename to `SyncPromise` . These are generally used to let outside threads/actors wait for/synchronize against an asynchronous operation.

File: dbux-graph-host/src/graph/SyncGraphBase.js [hunk 4]
```diff
@@ -403,10 +403,26 @@ class CallGraphNodes {
...
+  _handleContextNodeDisposed = (node) => {
+    let contexts;
+    if (node instanceof ContextNode) {
+      contexts = [node.state.context];
+    }
+    else if (node instanceof HoleNode) {
+      contexts = node.group.contexts;
+    }
+    else {
+      throw new Error(`Calling "_handleContextNodeDisposed" with non-ContextNode parameter`);
```
Comment (Domiii) [inline dbux-graph-host/src/graph/SyncGraphBase.js:419]: add `node` to the message, so we (kinda) know what it is?

**Review by Domiii — APPROVED** [review]
